name: simhacks
description: Information about SIM Cards and STK Applets.

markdown: redcarpet
pygments: true

navigation:
  - text: DEFCON 21 Talk
    url: /defcon-21/
    id: defcon-21
  - text: SIM Cards
    url: /sim-cards/
    id: sim-cards
  - text: JavaCard STK Applets
    url: /stk-applets/
    id: stk-applets
  - text: Android Emulator
    url: /android-emulator/
    id: android-emulator
  - text: Resources
    url: /resources/
    id: resources
